version: '3.1'

services:

  db:
    container_name: englenbot_db
    image: postgres:14
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./sql_scripts:/docker-entrypoint-initdb.d
      - ./db_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"